---
- name: Apply Amazon Linux CIS benchmarks
  block:
    # SSH Hardening (Section 5.2)
    - name: Disable SSH root login (CIS 5.2.8)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify: restart sshd

    # Password Policies (Section 5.4)
    - name: Set password expiration (CIS 5.4.1.1)
      ansible.builtin.command: chage --maxdays 90 root

    # Network Configuration (Section 3)
    - name: Disable IPv6 (CIS 3.1.1)
      ansible.builtin.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        state: present

    # File Permissions (Section 1)
    - name: Set strict umask (CIS 1.1.2)
      ansible.builtin.lineinfile:
        path: /etc/bashrc
        regexp: '^umask'
        line: 'umask 027'
        insertafter: EOF
---
- name: Apply Amazon Linux CIS hardening
  block:
    # Section 1: Initial Setup
    - name: Ensure mounting of cramfs is disabled (CIS 1.1.1.1)
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/CIS.conf
        line: "install cramfs /bin/true"
        create: yes

    # Section 5: Access, Authentication and Authorization
    - name: Disable SSH root login (CIS 5.2.8)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        notify: restart sshd

    # Section 6: System Maintenance
    - name: Set permissions on /etc/passwd (CIS 6.1.2)
      ansible.builtin.file:
        path: /etc/passwd
        mode: '0644'
        owner: root
        group: root