---
- name: Apply Ubuntu CIS benchmarks
  block:
    # SSH Configuration
    - name: Disable SSH root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
        state: present
      notify: restart ssh

    # Package Management
    - name: Remove unnecessary packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      loop:
        - telnetd
        - rsh-server

    # Filesystem Permissions
    - name: Set strict umask
      ansible.builtin.file:
        path: /etc/profile
        regexp: '^umask'
        line: 'umask 027'

---
- name: Apply Ubuntu CIS hardening
  block:
    # Section 1: Initial Setup
    - name: Ensure mounting of squashfs is disabled (CIS 1.1.1.2)
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/CIS.conf
        line: "install squashfs /bin/true"
        create: yes

    # Section 5: Access, Authentication and Authorization
    - name: Disable SSH root login (CIS 5.2.8)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
        notify: restart ssh

    # Section 6: System Maintenance
    - name: Set permissions on /etc/shadow (CIS 6.1.3)
      ansible.builtin.file:
        path: /etc/shadow
        mode: '0640'
        owner: root
        group: shadow

---
- name: Apply Ubuntu CIS hardening
  block:
    - name: Disable SSH root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        notify: restart ssh

    - name: Ensure apt-get updates are secure
      ansible.builtin.replace:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^\/\/\s*"\${distro_id}:\${distro_codename}-security";'
        replace: '"${distro_id}:${distro_codename}-security";'