---
- name: CIS Hardening for Amazon Linux 2023
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3  # 🚀 Explicitly set correct Python version
    ansible_pkg_mgr: dnf  # 🚀 Force correct package manager
    sshd_config_path: /etc/ssh/sshd_config

  tasks:
    - name: Disable root login via SSH
      lineinfile:
        path: "{{ sshd_config_path }}"
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Install auditd for system monitoring (Explicitly set DNF backend)
      ansible.builtin.dnf:
        name: auditd
        state: present
        use_backend: dnf5

    - name: Enable auditd
      ansible.builtin.service:
        name: auditd
        enabled: true
        state: started

    - name: Install cronie (for security updates)
      ansible.builtin.dnf:
        name: cronie
        state: present
        use_backend: dnf5

    - name: Configure automatic security updates
      ansible.builtin.cron:
        name: "Automatic security updates"
        minute: "0"
        hour: "2"
        job: "dnf -y update --security"
