# ---
# - name: CIS Level 1 Hardening - Amazon Linux 2023
#   hosts: all
#   become: true
#   gather_facts: true

#   vars:
#     sshd_config_path: /etc/ssh/sshd_config
#     ansible_pkg_mgr: dnf  # Force package manager to dnf

#   tasks:
#     - name: Ensure security packages are installed
#       ansible.builtin.dnf:
#         name:
#           - audit
#           - cronie
#           - fail2ban
#         state: present
#         use_backend: dnf5  # Explicitly specify backend

#     - name: Disable root SSH login
#       ansible.builtin.lineinfile:
#         path: "{{ sshd_config_path }}"
#         regexp: '^#?PermitRootLogin'
#         line: 'PermitRootLogin no'
#         validate: '/usr/sbin/sshd -t -f %s'
#       notify: restart sshd

#     - name: Configure automatic security updates
#       ansible.builtin.cron:
#         name: "Automatic security updates"
#         minute: "0"
#         hour: "2"
#         job: "dnf -y update --security"

#   handlers:
#     - name: restart sshd
#       ansible.builtin.service:
#         name: sshd
#         state: restarted



---
- name: CIS Hardening for Amazon Linux 2023
  hosts: all
  become: true
  tasks:
    - name: Disable root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Set password max days to 90
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS   90'

    - name: Set minimum password length to 14
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: '^minlen'
        line: 'minlen = 14'

    - name: Ensure auditd is installed
      package:
        name: audit
        state: present

    - name: Enable and start auditd
      service:
        name: auditd
        enabled: true
        state: started