---
- name: CIS Level 1 Hardening - Amazon Linux 2023
  hosts: all
  become: true

  vars:
    sshd_config_path: /etc/ssh/sshd_config

  tasks:
    - name: Disable root login via SSH
      lineinfile:
        path: "{{ sshd_config_path }}"
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Install auditd for system monitoring
      package:
        name: audit
        state: present

    - name: Enable auditd
      service:
        name: auditd
        enabled: true
        state: started

    - name: Install cronie (for security updates)
      package:
        name: cronie
        state: present

    - name: Configure automatic security updates
      cron:
        name: "Automatic security updates"
        minute: "0"
        hour: "2"
        job: "dnf -y update --security"
