---
- name: CIS Level 1 Hardening - Ubuntu 24.04
  hosts: all
  become: true

  vars:
    sshd_config_path: /etc/ssh/sshd_config

  tasks:
    - name: Disable root login via SSH
      lineinfile:
        path: "{{ sshd_config_path }}"
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Set password max days to 90
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS   90'

    - name: Enable automatic security updates
      package:
        name: unattended-upgrades
        state: present

    - name: Configure fail2ban for SSH
      apt:
        name: fail2ban
        state: present

    - name: Harden SSH login settings
      blockinfile:
        path: "{{ sshd_config_path }}"
        block: |
          PermitRootLogin no
          PermitUserEnvironment no
          MaxAuthTries 4
          IgnoreRhosts yes
          LoginGraceTime 60
        marker: "# {mark} ANSIBLE MANAGED BLOCK - SSH HARDENING"

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
