---
- name: CIS Level 1 Hardening - Ubuntu 24.04
  hosts: all
  become: true

  vars:
    sshd_config_path: /etc/ssh/sshd_config

  tasks:
    - name: Disable root login via SSH
      lineinfile:
        path: "{{ sshd_config_path }}"
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Configure password policies
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS   90'

    - name: Enable automatic security updates
      package:
        name: unattended-upgrades
        state: present

    - name: Install and configure fail2ban
      package:
        name: fail2ban
        state: present

    - name: Ensure SSH is installed
      ansible.builtin.apt:
        name: openssh-server
        state: present
      when: ansible_service_mgr == "systemd"

    - name: Restart SSH service correctly
      ansible.builtin.service:
        name: "{{ 'sshd' if ansible_facts.services['sshd'] is defined else 'ssh' }}"
        state: restarted
      when: ansible_service_mgr == "systemd"
