---
- name: Harden Ubuntu Server
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    - name: Install security packages
      apt:
        name:
          - ufw
          - auditd
          - fail2ban
          - unattended-upgrades
        state: present

    - name: Harden SSH configuration
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          Protocol 2
          PermitRootLogin no
- name: Install cron if missing
  package:
    name: cronie
    state: present

- name: Ensure cron service is running
  service:
    name: crond
    enabled: true
    state: started

- name: Configure automatic security updates
  cron:
    name: "Automatic security updates"
    minute: "0"
    hour: "2"
    job: "dnf -y update --security"
