name: Reusable AMI Builder
on:
  workflow_call:
    inputs:
      os_type:
        description: 'Select OS to build'
        required: true
        type: string
      region:
        description: 'AWS Region'
        required: true
        type: string
      role_arn:
        description: 'IAM Role ARN for Packer'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/PackerInstanceProfile
          aws-region: ${{ inputs.region }}


      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Validate Packer Template
        run: |
          cd packer
          packer init .
          packer validate ${{ inputs.os_type }}.pkr.hcl

      - name: Build AMI
        run: |
          cd packer
          PACKER_LOG=1 packer build -debug -var-file="../variables/${{ inputs.os_type }}.pkrvars.hcl" ${{ inputs.os_type }}.pkr.hcl
