name: Call Golden AMI Build

on:
  workflow_dispatch:
    inputs:
      image_type:
        description: 'Choose image type: amazon or ubuntu'
        required: true
        default: 'amazon'

permissions:
  id-token: write
  contents: read

jobs:
  call-build-ami:
    uses: ./.github/workflows/build-ami-reusable.yml  # Reusable workflow file path
    with:
      image_type: ${{ github.event.inputs.image_type }}  # Pass image_type from user input
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SUBNET_ID: ${{ secrets.AWS_SUBNET_ID }}
      AWS_IAM_INSTANCE_PROFILE: ${{ secrets.AWS_IAM_INSTANCE_PROFILE }}
      AWS_SOURCE_AMAZON_AMI: ${{ secrets.AWS_SOURCE_AMAZON_AMI }}
      AWS_SOURCE_UBUNTU_AMI: ${{ secrets.AWS_SOURCE_UBUNTU_AMI }}
