name: Build AMI Caller Workflow

on:
  workflow_dispatch:
    inputs:
      image_type:
        description: 'Choose the image type to build (amazon or ubuntu)'
        required: true
        type: choice
        options:
          - amazon
          - ubuntu

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/build-ami-reusable.yml
    with:
      image_type: ${{ github.event.inputs.image_type }}
