name: AMI Builder - Core

on:
  workflow_call:
    inputs:
      os_type:
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_REGION:
        required: true
      AWS_SUBNET_ID:
        required: true
      AWS_IAM_INSTANCE_PROFILE:
        required: true
      AWS_SOURCE_AMAZON_AMI:
        required: true
      AWS_SOURCE_UBUNTU_AMI:
        required: true

# Critical fix for OIDC
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: golden-ami-builder-${{ github.run_number }}

      - name: Determine source AMI
        id: ami-selector
        run: |
          if [ "${{ inputs.os_type }}" = "amazon-linux" ]; then
            echo "SOURCE_AMI=${{ secrets.AWS_SOURCE_AMAZON_AMI }}" >> $GITHUB_OUTPUT
          else
            echo "SOURCE_AMI=${{ secrets.AWS_SOURCE_UBUNTU_AMI }}" >> $GITHUB_OUTPUT
          fi

      - name: Build AMI
        working-directory: ./packer
        run: |
          packer build \
            -var "source_ami=${{ steps.ami-selector.outputs.SOURCE_AMI }}" \
            -var "subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
            -var "iam_instance_profile=${{ secrets.AWS_IAM_INSTANCE_PROFILE }}" \
            -var "region=${{ secrets.AWS_REGION }}" \
            templates/${{ inputs.os_type }}.pkr.hcl