name: AMI Builder - Core

on:
  workflow_call:
    inputs:
      os_type:
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_REGION:
        required: true
      AWS_SUBNET_ID:
        required: true
      AWS_IAM_INSTANCE_PROFILE:
        required: true
      AWS_SOURCE_AMAZON_AMI:
        required: true
      AWS_SOURCE_UBUNTU_AMI:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: golden-ami-builder-${{ github.run_id }}

      - name: Determine source AMI
        id: ami-selector
        run: |
          if [ "${{ inputs.os_type }}" = "amazon-linux" ]; then
            echo "SOURCE_AMI=${{ secrets.AWS_SOURCE_AMAZON_AMI }}" >> $GITHUB_OUTPUT
          else
            echo "SOURCE_AMI=${{ secrets.AWS_SOURCE_UBUNTU_AMI }}" >> $GITHUB_OUTPUT
          fi

      - name: Setup Packer environment
        working-directory: ./packer
        run: |
          # Install latest Packer version
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install -y packer

          # Initialize plugins
          packer init .

          # Verify plugins
          echo "Installed Packer plugins:"
          packer plugins installed || echo "Plugin check failed - proceeding anyway"


          - name: Build AMI
          working-directory: ./packer
          run: |
            echo "=== VERIFYING FILES ==="
            ls -la ./scripts/
            ls -la ../ansible/playbooks/
            
            # Install plugins
            packer init -upgrade .
            
            # Build with absolute paths
            PACKER_LOG=1 packer build \
              -var "source_ami=${{ steps.ami-selector.outputs.SOURCE_AMI }}" \
              -var "subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
              -var "iam_instance_profile=${{ secrets.AWS_IAM_INSTANCE_PROFILE }}" \
              -var "region=${{ secrets.AWS_REGION }}" \
              -var "script_path=${GITHUB_WORKSPACE}/golden-ami-factory/packer/scripts/bootstrap.sh" \
              -var "playbook_path=${GITHUB_WORKSPACE}/golden-ami-factory/ansible/playbooks/cis-hardening.yml" \
              templates/${{ inputs.os_type }}.pkr.hcl