name: Build Hardened AMI
on:
  workflow_dispatch:
    inputs:
      os_type:
        description: 'Select OS to build'
        required: true
        type: choice
        options:
          - ubuntu
          - amazonlinux
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'

jobs:
  build:
    uses: ./.github/workflows/ami-reusable.yml
    with:
      os_type: ${{ inputs.os_type }}
      region: ${{ inputs.region }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
