name: Build Hardened AMI
on:
  workflow_dispatch:
    inputs:
      os_type:
        description: 'Select OS to build'
        required: true
        default: 'ubuntu'
        type: choice
        options:
          - ubuntu
          - amazonlinux
      region:
        description: 'AWS region'
        required: true
        default: 'us-east-1'
      iam_role:
        description: 'IAM role for Packer'
        required: true
        default: 'GitHubActionsPackerRole'

permissions:
  id-token: write
  contents: read

jobs:
  build-ami:
    name: Build ${{ inputs.os_type }} AMI
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsPackerRole
          aws-region: us-east-1
          audience: sts.amazonaws.com  # THIS IS CRUCIAL

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::767398107227:role/PackerInstanceProfile  # Must match EXACT role name
          aws-region: us-east-1
          audience: sts.amazonaws.com  # Critical for OIDC

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Validate Packer template
        run: |
          cd packer
          packer validate ${{ inputs.os_type }}.pkr.hcl

      - name: Build AMI with Packer
        run: |
          cd packer
          packer build \
            -var-file="../variables/${{ inputs.os_type }}.pkrvars.hcl" \
            ${{ inputs.os_type }}.pkr.hcl