name: Call Golden AMI Build

on:
  workflow_dispatch:
    inputs:
      image_type:
        description: 'Choose image type: amazon or ubuntu'
        required: true
        default: 'amazon'

permissions:
  id-token: write
  contents: read

jobs:
  call-build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: 'latest'

      - name: Initialize Packer
        run: |
          packer init .

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build AMI
        run: |
          if [ "${{ github.event.inputs.image_type }}" = "amazon" ]; then
            packer build \
              -var "subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
              -var "iam_instance_profile=${{ secrets.AWS_IAM_INSTANCE_PROFILE }}" \
              -var "source_ami=${{ secrets.AWS_SOURCE_AMAZON_AMI }}" \
              packer/amazon-linux.pkr.hcl
          elif [ "${{ github.event.inputs.image_type }}" = "ubuntu" ]; then
            packer build \
              -var "subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
              -var "iam_instance_profile=${{ secrets.AWS_IAM_INSTANCE_PROFILE }}" \
              -var "source_ami=${{ secrets.AWS_SOURCE_UBUNTU_AMI }}" \
              packer/ubuntu.pkr.hcl
          else
            echo "Invalid image_type: ${{ github.event.inputs.image_type }}"
            exit 1
          fi
