name: Build Golden AMI with OIDC

on:
  workflow_call:
    inputs:
      ami-type:
        description: 'Type of AMI to create (Amazon Linux or Ubuntu)'
        required: true
        type: string

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials (via OIDC)
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # IAM role ARN
        aws-region: ${{ secrets.AWS_REGION }}       # AWS region (e.g., us-west-2)

    - name: Build Amazon Linux AMI (if chosen)
      if: ${{ inputs.ami-type == 'amazon-linux' }}
      run: |
        cd packer
        packer build amazon-linux.pkr.hcl

    - name: Build Ubuntu AMI (if chosen)
      if: ${{ inputs.ami-type == 'ubuntu' }}
      run: |
        cd packer
        packer build ubuntu.pkr.hcl
