name: Reusable AMI Build

on:
  workflow_call:
    inputs:
      image_type:
        description: 'Choose image type: amazon or ubuntu'
        required: true
        type: string  # ✅ Type added

    secrets:
      AWS_ACCESS_KEY_ID: {}
      AWS_SECRET_ACCESS_KEY: {}
      AWS_REGION: {}
      AWS_SUBNET_ID: {}
      AWS_IAM_INSTANCE_PROFILE: {}
      AWS_SOURCE_AMAZON_AMI: {}
      AWS_SOURCE_UBUNTU_AMI: {}
      AWS_SESSION_TOKEN: {}  # Optional but added for completeness

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: '1.8.0'  # or your required version

      - name: Initialize Packer plugins
        run: |
          cd packer
          packer init .

      - name: Run Packer Build
        run: |
          if [ "${{ inputs.image_type }}" = "amazon" ]; then
            packer build \
              -var "subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
              -var "iam_instance_profile=${{ secrets.AWS_IAM_INSTANCE_PROFILE }}" \
              -var "source_ami=${{ secrets.AWS_SOURCE_AMAZON_AMI }}" \
              packer/amazon-linux.pkr.hcl
          elif [ "${{ inputs.image_type }}" = "ubuntu" ]; then
            packer build \
              -var "subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
              -var "iam_instance_profile=${{ secrets.AWS_IAM_INSTANCE_PROFILE }}" \
              -var "source_ami=${{ secrets.AWS_SOURCE_UBUNTU_AMI }}" \
              packer/ubuntu.pkr.hcl
          else
            echo "Invalid image_type: ${{ inputs.image_type }}"
            exit 1
          fi
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
