name: AMI Builder - Trigger

on:
  workflow_dispatch:
    inputs:
      os_type:
        description: 'OS to build'
        required: true
        type: choice
        options: [amazon-linux, ubuntu]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-ami-reusable.yml
    with:
      os_type: ${{ inputs.os_type }}
    secrets: inherit