name: AMI Builder - Trigger

on:
  workflow_dispatch:

jobs:
  build-amazon-linux:
    uses: ./.github/workflows/build-ami-reusable.yml
    secrets: inherit
    with:
      os_type: "amazon-linux"  # No environment parameter needed
      
  build-ubuntu:
    uses: ./.github/workflows/build-ami-reusable.yml
    secrets: inherit
    with:
      os_type: "ubuntu"