name: AMI Builder - Trigger

on:
  workflow_dispatch:

permissions:
  id-token: write  # This must be declared in the caller workflow
  contents: read

jobs:
  build-amazon-linux:
    uses: ./.github/workflows/build-ami-reusable.yml
    with:
      os_type: "amazon-linux"
    secrets: inherit

  build-ubuntu:
    uses: ./.github/workflows/build-ami-reusable.yml
    with:
      os_type: "ubuntu"
    secrets: inherit